name: task
description: Flutter project with Artisan.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
 
  cupertino_icons: ^1.0.2
  
  #Router
  go_router: ^14.2.7

  #provider
  provider: ^6.1.5+1
  
  #UI
  flutter_screenutil: ^5.7.0


  #DI
  get_it: ^7.2.0
  injectable: ^2.1.0


  
  #Firebase
  firebase_core: ^3.6.0

  #Information
  logger: ^2.4.0

  #toast
  fluttertoast: ^8.2.1

 
  
  #Other Dependencies
  freezed_annotation: ^2.2.0
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.4.0
  injectable_generator: ^2.1.4

  artisan:
    git:
      url: https://github.com/Wolfiz-2-0/artisan
      ref: beta

  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    
flutter:
  uses-material-design: true
  assets:
    - assets/pngs/
