////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import '../../../../infrastructure/repository.dart';
import '../usecases/login.dart';
import '../usecases/register.dart';
import '../usecases/google_login.dart';
////********** END IMPORTS **********////

abstract class AuthRepository extends Repository {
////********** START METHODS **********////
  /// [LoginUsecaseInput] is received to [login] method as parameter
  /// [LoginUsecaseOutput] is returned from [login] method
  Future<LoginUsecaseOutput> login(LoginUsecaseInput input);
    

  /// [RegisterUsecaseInput] is received to [register] method as parameter
  /// [RegisterUsecaseOutput] is returned from [register] method
  Future<RegisterUsecaseOutput> register(RegisterUsecaseInput input);


  /// [GoogleLoginUsecaseInput] is received to [googleLogin] method as parameter
  /// [GoogleLoginUsecaseOutput] is returned from [googleLogin] method
  Future<GoogleLoginUsecaseOutput> googleLogin(GoogleLoginUsecaseInput input);

////********** END METHODS **********////
}
  
